name: Deploy Storybook

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build Storybook
        run: pnpm build; pnpm tailwind; pnpm build-storybook

      - name: Copy build files
        run: cp -r storybook-static deploy

      - name: Deploy preview
        if: github.event_name == 'pull_request'
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: deploy
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto

      - name: Deploy main
        # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy
          branch: gh-pages
          clean-exclude: pr-preview
          force: false


