name: PR Checks

on:
  pull_request:

jobs:
  pr-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run PR check
        run: pnpm pr:check
